version: '3.12'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-ref
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - .:/FastApiRef
    ports:
      - "8000:8000"
